name: Deploy de la pagina
on:
  push:
    branches:
      - main

jobs:
  deploy-page:
  steps:

  - name: Valentina
    uses:

  - name: Deploy
    uses: 
    with:
      branch: gh-pages
      folder: .
